name: Maven Package

# Déclenche ce workflow sur un push de tag ou sur release créée
on:
  push:
    # Pousse un tag de version (ex. v1.0.0)
    tags:
      - 'v*.*.*'
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github                   # doit matcher <id> de distributionManagement du pom.xml
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          settings-path: ${{ github.workspace }}  # emplacement du settings.xml

      - name: Build and Deploy to GitHub Packages
        run: mvn -B deploy --settings $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # pour le serveur Maven 'github'
